Add GOWORK env variable when go vet is run
openstack-k8s-operators/openstack-k8s-operators-ci pull request #56
Opened 2022-11-29 11:03 UTC by fmount

The cinder-operator patch [1] introduces the `go.work` file within the repository with the goal of automating the way we deal with multi module dependencies.
However, the side effect of having a versioned `go.work` in the repo is the failure of the `govet` CI script because `GOWORK` is automatically set to `on`. This patch fixes the CI run on the cinder-operator PR [1], introducing a `GOWORK` variable (which is set to off by default) to make sure we can successfully run this check regardless of the approach.

[1] https://github.com/openstack-k8s-operators/cinder-operator/pull/79

Signed-off-by: Francesco Pantano <fpantano@redhat.com>

2022-11-29 11:19 UTC, gibizer commented
repos having go.work file checked in already adding `GOWORK=off` to the CI make target to fix this. After this land such repos can remove the `GOWORK=off` from their Makefile.

2022-11-29 15:59 UTC, stuggi approved these changes
/lgtm

2022-11-29 17:08 UTC, Akrog requested changes
We also need to modify Dockerfile to support `GOWORK`

2022-11-30 10:26 UTC, Akrog approved these changes

2022-11-30 10:42 UTC, merged